name: Application testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Pre Test:
    runs-on: ubuntu-latest

    steps: 
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install pipenv==2020.11.15
          pipenv sync
          pipenv shell

      - name: Download config file
        run: |
          pwd
          python download_config.py ${{ secrets.CONFIGURATION_FILE_ID}} ${{ secrets.GDRIVE_API_KEY }}

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: pipenv run pytest