name: Application testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Pre-Test:
    runs-on: ubuntu-latest

    steps: 
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install pipenv==2020.11.15
          pipenv install requests

      - name: Download config file
        run: pipenv run python download_config.py ${{ secrets.CONFIGURATION_FILE_ID }} ${{ secrets.GDRIVE_API_KEY }}

  Test:
    runs-on: ubuntu-latest
    needs: Pre-Test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pipenv==2020.11.15
          pipenv sync

      - name: Run tests
        run: |
          export FLASK_ENV=testing
          pipenv run pytest