name: Application testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pipenv==2020.11.15
          pipenv sync
      
      - name: Download config file
        run: pipenv run python download_config.py ${{ secrets.CONFIGURATION_FILE_ID }} ${{ secrets.GDRIVE_API_KEY }}

      - name: Download google credentails file
        run: |
          pipenv run python download_google_creds.py ${{ secrets.GOOGLE_SERVICE_ACC_CREDENTIALS_ID }} ${{ secrets.GDRIVE_API_KEY }}
          ls
          cat swito-google-creds.json

      - name: Commit configuration files
        run: |
          git add -f configuration.py swito-google-creds.json
          git commit -m "added secret files"

      - name: Run tests
        run: pipenv run pytest